<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.8 setup script
 * Date: Thu, 08 Dec 2011 14:11:43 +0800
 */

$cfg['DefaultLang'] = 'zh_CN';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['blowfish_secret'] = 'west3306';
$cfg['AllowArbitraryServer'] = true;
$cfg['LoginCookieRecall'] = false;
$cfg['VersionCheck'] = false;
$cfg['UserprefsDisallow'] = array('VersionCheck');
?>